name: Gradle Build

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to build with"
        required: false
        type: number
        default: 25
      codecov-enabled:
        description: "Whether to upload coverage report to Codecov"
        required: false
        type: boolean
        default: false
      codecov-files:
        description: "Paths to XML code coverage reports"
        required: false
        type: string
        default: ""
    secrets:
      CODECOV_TOKEN:
        description: "Access token to Codecov"
        required: false

jobs:
  build:
    name: Build (Java ${{ inputs.java-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: "${{ inputs.java-version }}"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-build-${{ runner.os }}-java-${{ inputs.java-version }}-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-build-${{ runner.os }}-java-${{ inputs.java-version }}-

      - name: Gradle Build
        env:
          GRADLE_OPTS: >-
            -Dorg.gradle.configuration-cache=false
            -Dorg.gradle.daemon=false
            -Dorg.gradle.parallel=false
            -Dorg.gradle.workers.max=1
        run: ./gradlew build

      - name: Upload JaCoCo report to Codecov
        if: ${{ inputs.codecov-enabled }}
        uses: codecov/codecov-action@v7
        with:
          disable_search: true
          files: ${{ inputs.codecov-files }}
          token: ${{ secrets.CODECOV_TOKEN }}
